<code> ::= <module> <sep> <action> <sep> <subgraph>
<sep> ::= " | "
<subgraph> ::= <word> | <sub>
<sub> ::= "(" <code> ")"
<module> ::= <word>
<action> ::= <word>
<word> ::= <char> | <word> <char>
<char> ::= [a-z]
