//
// Created by velocitatem on 11/22/23.
//
/*
 * The parser takes the stream of tokens generated by your lexer and constructs an Abstract Syntax Tree (AST), which represents the grammatical structure of your program.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <lexer.h>
#include <tokens.h>
#include <stdio.h>


typedef struct {
    Lexer* lexer;
    Token current;
    Token previous;
    bool hadError;
    bool panicMode;
} Parser;

typedef struct ParserNode {
    Token token;
    struct ParserNode* next;
    struct ParserNode* prev;
} ParserNode;

typedef struct {
    ParserNode* head;
    ParserNode* tail;
    int size;
} ParserList;

Parser* initParser(Lexer* lexer) {
    Parser* parser = malloc(sizeof(Parser));
    parser->lexer = lexer;
    parser->hadError = false;
    parser->panicMode = false;
    return parser;
}

void freeParser(Parser* parser) {
    free(parser);
}

