name: Build Executable Linux

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Directory
      run: mkdir -p build

    - name: Run CMake
      run: |
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Upload Linux Executable
      uses: actions/upload-artifact@v2
      with:
        name: linux-executable
        path: build/GRAP  # Replace with your actual executable path
